name: Bug Report
description: Report a bug or unexpected behavior
title: "Bug: [brief description]"
labels: ["bug"]
body:
  - type: dropdown
    id: crate
    attributes:
      label: Affected Crate
      description: Which crate is affected?
      options:
        - sf-client
        - sf-auth
        - sf-rest
        - sf-bulk
        - sf-metadata
        - sf-tooling
        - Multiple / Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a client with `SalesforceRestClient::new(...)`
        2. Call `client.query::<Account>("SELECT Id FROM Account")`
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual Behavior
      description: What you expected to happen and what actually happened.
      placeholder: |
        **Expected:** Query returns successfully with `QueryResult<Account>`
        **Actual:** Returns error `ErrorKind::Serialization("missing field 'Id'")`
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.88.0 (e7e1dc158 2025-06-04)"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15.2 / Ubuntu 24.04 / Windows 11"
    validations:
      required: false

  - type: input
    id: crate-version
    attributes:
      label: Crate Version
      description: Version of the affected busbar-sf-api crate.
      placeholder: "0.0.2"
    validations:
      required: false
